# Generated by Django 3.2.3 on 2021-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idZapatilla', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Zapatilla')),
                ('tallaZapatilla', models.CharField(max_length=5, verbose_name='Talla Zapatilla')),
            ],
        ),
    ]
