# Generated by Django 3.2.3 on 2021-06-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('idRopa', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Ropa')),
                ('tallaRopa', models.CharField(max_length=5, verbose_name='Talla de Ropa')),
            ],
        ),
        migrations.CreateModel(
            name='Zapatillas',
            fields=[
                ('idZapatilla', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Zapatilla')),
                ('tallaZapatilla', models.CharField(max_length=5, verbose_name='Talla Zapatilla')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
