# Generated by Django 3.2.3 on 2021-06-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_auto_20210615_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ropa',
        ),
        migrations.DeleteModel(
            name='Zapatillas',
        ),
    ]
